// https://ipsc.ksp.sk/2016/real/problems/c.html
#include <iostream>
#include <string>

using namespace std;

const string STR [] = {
    "Click on the orange square.",
    "Click on the pink square.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the blue square.",
    "Click on the pink wide rectangle.",
    "Click on the green square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange square.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the pink square.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the red square.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the blue square.",
    "Click on the green wide rectangle.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the pink square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the green wide rectangle.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the blue square.",
    "Click on the green wide rectangle.",
    "Click on the red square.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red square.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the orange square.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the blue wide rectangle.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the orange square.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the orange square.",
    "Click on the yellow wide rectangle.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the orange square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the pink wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the blue wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue square.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the blue square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange square.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the orange square.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue square.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue square.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the green wide rectangle.",
    "Click on the pink square.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow square.",
    "Click on the orange square.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the yellow square.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the red square.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the blue wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square and then click on the blue wide rectangle.",
    "Click on the yellow wide rectangle and then click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue square and then click on the red square.",
    "Click on the orange square and then click on the blue square.",
    "Click on the blue square and then click on the green wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle and then click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the pink wide rectangle and then click on the yellow wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow square and then click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the orange square and then click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the red wide rectangle and then click on the orange square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle and then click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the red square and then click on the orange square.",
    "Click on the yellow square and then click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the blue square and then click on the red square.",
    "Click on the pink square and then click on the green wide rectangle.",
    "Click on the yellow square and then click on the orange square.",
    "Click on the orange wide rectangle and then click on the blue square.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the pink wide rectangle and then click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle and then click on the blue square.",
    "Click on the pink square.",
    "Click on the yellow square.",
    "Click on the orange square and then click on the pink square.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green square and then click on the pink wide rectangle.",
    "Click on the yellow wide rectangle and then click on the red wide rectangle.",
    "Click on the yellow wide rectangle and then click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the blue square and then click on the orange square.",
    "Click on the pink wide rectangle and then click on the blue square.",
    "Click on the pink wide rectangle and then click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the red wide rectangle and then click on the green wide rectangle.",
    "Click on the blue square and then click on the yellow wide rectangle.",
    "Click on the pink square and then click on the orange square.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the green square and then click on the green wide rectangle.",
    "Click on the orange wide rectangle and then click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue square and then click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle and then click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the blue square and then click on the yellow wide rectangle.",
    "Click on the green wide rectangle and then click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the pink wide rectangle and then click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square and then click on the orange square.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink square and then click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle and then click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle and then click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange square and then click on the pink square.",
    "Click on the yellow square and then click on the green wide rectangle.",
    "Click on the red wide rectangle and then click on the pink square.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle and then click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red square and then click on the blue wide rectangle.",
    "Click on the blue square.",
    "Click on the red square and then click on the pink wide rectangle.",
    "Click on the green square and then click on the yellow square.",
    "Click on the green square.",
    "Click on the green wide rectangle and then click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the pink square and then click on the green square.",
    "Click on the orange square and then click on the red square.",
    "Click on the red square.",
    "Click on the blue wide rectangle and then click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the pink wide rectangle and then click on the blue square.",
    "Click on the green square and then click on the yellow wide rectangle.",
    "Click on the blue wide rectangle and then click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the green square and then click on the yellow square.",
    "Click on the green wide rectangle and then click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the yellow square and then click on the blue square.",
    "Click on the orange square and then click on the orange wide rectangle.",
    "Click on the blue square.",
    "Click on the red square and then click on the green square.",
    "Click on the yellow wide rectangle and then click on the blue square.",
    "Click on the yellow wide rectangle and then click on the green square.",
    "Click on the pink wide rectangle and then click on the blue wide rectangle.",
    "Click on the blue square.",
    "Click on the blue square and then click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the red square and then click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the orange wide rectangle and then click on the red square.",
    "Click on the green wide rectangle and then click on the yellow square.",
    "Click on the red wide rectangle and then click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow wide rectangle and then click on the blue square.",
    "Click on the pink square.",
    "Click on the red square and then click on the orange square.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle and then click on the orange square.",
    "Click on the yellow square.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the red square and then click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink square and then click on the pink wide rectangle.",
    "Click on the blue wide rectangle and then click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange square and then click on the orange wide rectangle.",
    "Click on the blue wide rectangle and then click on the green square.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle and then click on the green square.",
    "Click on the pink square.",
    "Click on the yellow square and then click on the blue wide rectangle.",
    "Click on the yellow wide rectangle and then click on the green square.",
    "Click on the yellow square and then click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle and then click on the yellow wide rectangle.",
    "Click on the blue square and then click on the red square.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle and then click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle and then click on the blue wide rectangle.",
    "Click on the blue wide rectangle and then click on the blue square.",
    "Click on the orange wide rectangle and then click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle and then click on the orange square.",
    "Click on the yellow wide rectangle and then click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green square and then click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the green square and then click on the blue wide rectangle.",
    "Click on the pink square and then click on the blue square.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square and then click on the red square.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the blue square.",
    "Click on the pink square."
    };

const string OUT [] = {
    "309 80", // red wide
    "520 78", // yellow wide
    "301 178", // green wide
    "497 175", // orange wide
    "296 274", // blue wide
    "516 278", // pink wide

    "72 75", // red squre
    "176 72", // yellow squre
    "68 183", // green squre
    "172 177", // orange squre
    "71 275", // blue squre
    "189 278" // pink squre
};

const string CH [] = {
    "red wide",
    "yellow wide",
    "green wide",
    "orange wide",
    "blue wide",
    "pink wide", ///
    
    "red square",
    "yellow square",
    "green square",
    "orange square",
    "blue square",
    "pink square", ///
};

void each(const string &s) {
    int a = s.find("and then");
    const int size = sizeof(CH) / sizeof(string);
    if (a == string::npos) {
        for (int i = 0; i < size; i++) {
            if (s.find(CH[i]) != string::npos) {
                cout << OUT[i] << "\nnext\n";
                return;
            }
        }
    } else {
        string s1 = s.substr(0, a);
        string s2 = s.substr(a, s.size() - a);

        for (int i = 0; i < size; i++) {
            if (s1.find(CH[i]) != string::npos) {
                cout << OUT[i] << "\n";
                break;
            }
        }
        for (int i = 0; i < size; i++) {
            if (s2.find(CH[i]) != string::npos) {
                cout << OUT[i] << "\nnext\n";
                break;
            }
        }
    }
}

int main() {
    int size = sizeof(STR) / sizeof(string);
    cout << OUT[0] << "\nnext\n";
    for (int i = 0; i < size; i++) {
        each(STR[i]);
    }
    cout << "done\n";
    return 0;
}

